table Dim_Product
	lineageTag: 3f58fad0-ebdc-47d0-8a2f-b629292846ca

	column item
		dataType: string
		lineageTag: eb378e9e-9e05-499a-a2f0-5c356afec245
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 0686345a-bb35-4e19-a0a1-53a81368261d
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: 691b7a12-3406-4ae8-90fd-d3f94f1f17e5
		summarizeBy: none
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	partition Dim_Product = m
		mode: import
		source =
				let
				    Source = Raw_Sales,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"category", "item", "unit_price"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Other Columns",{"item", "category", "unit_price"}),
				    #"Removed Duplicates" = Table.Distinct(#"Reordered Columns")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

